### ISSUE TITLE
babel-runtime@~5.8.20 dependency 

### ISSUE THREAD

**Issue by pepepaco** [xieguanglei/react-pace-progress#1]
Im getting the following error:

npm WARN react-pace-progress@1.0.0 requires a peer of babel-runtime@~5.8.20 but none was installed.
my current  babel version is "babel-runtime": "^6.11.6" and i cant downgrade it as is required for charts and other stuff.

the loading bar is not showing, any help would be really appreciated. regards

**Comment by pepepaco** [comment]
the loading bar is actually shown but i can't get rid of the warning, I can live with it, but it would be better not to have it.

thanks.

**Comment by xieguanglei** [comment]
@pepepaco updated in react-pace-progress@1.0.1
